spring:
  config:
    activate:
      on-profile: docker
    import:
      - "optional:file:./.env[.properties]"
      - "optional:file:./mopl-socket/.env[.properties]"
  datasource:
    url: jdbc:mysql://mysql:3306/mopl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MOPL_DB_USERNAME:app}
    password: ${MOPL_DB_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: ${MOPL_DDL_AUTO:update}
  data:
    redis:
      host: ${MOPL_REDIS_HOST:redis}
      port: ${MOPL_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${MOPL_KAFKA_BOOTSTRAP:kafka:29092}

server:
  port: ${MOPL_PORT:8081}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_VALIDITY:86400}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_VALIDITY:604800}
