spring:
  config:
    activate:
      on-profile: staging
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_AUTH_TOKEN}
      ssl:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_API_KEY}"
        password="${KAFKA_API_SECRET}";

server:
  port: 8081

logging:
  level:
    root: INFO
    io.mopl: INFO

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_VALIDITY:86400}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_VALIDITY:604800}

app:
  cors:
    allowed-origins: "*"
