server {
    # 80 포트로 들어오는 HTTP 요청을 받는다.
    listen 80;
    # 도메인이 정해져 있지 않은 로컬/개발환경에서 모든 호스트를 받는 설정
    server_name _;

    # 1) Frontend (SPA) (정적 파일 서빙)
    # Nginx가 정적 파일을 찾을 웹 루트 경로
    # docker-compose에서 이 경로에 프론트 빌드(dist/build)를 마운트 - 저는 build 안에 코드잇에서 제공받은 dist 폴더를 넣었습니다.
    root /usr/share/nginx/html;
    # 기본으로 열어줄 파일
    index index.html;

    # 정적 파일 캐시(선택)
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        # SPA(React, vue) 라우팅 지원을 위한 설정
        # 요청한 경로에 해당 파일이 실제로 존재하면($uri) 그 파일을 주고,
        # 없으면(index.html)로 돌려서 프론트 라우터가 처리하게 한다.
        # 예시 : /profile 같은 URL로 새로고침해도 404가 아니라 index.html을 내려줌
        try_files $uri $uri/ /index.html;
    }
    # (선택) 헬스체크
    location = /health {
        return 200 "ok";
    }
}
