server:
  forward-headers-strategy: framework

spring:
  application:
    name: mopl-api
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: io.mopl.core.event.*
  messages:
    basename: messages,ValidationMessages
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "${OAUTH2_BASE_URL:http://localhost:8080}/login/oauth2/code/google"

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "${OAUTH2_BASE_URL:http://localhost:8080}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

security:
  cookie:
    same-site: ${COOKIE_SAME_SITE:Lax}
    csrf:
      name: ${CSRF_COOKIE_NAME:XSRF-TOKEN}
      http-only: ${CSRF_HTTP_ONLY:false}
    refresh-token:
      name: ${REFRESH_TOKEN_NAME:REFRESH_TOKEN}
      http-only: ${REFRESH_TOKEN_HTTP_ONLY:true}
      max-age: ${REFRESH_TOKEN_MAX_AGE:604800}

oauth2:
  redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

mopl:
  init:
    admin:
      email: ${MOPL_ADMIN_EMAIL:admin@mopl.io}
      password: ${MOPL_ADMIN_PASSWORD:1234}
      name: ${MOPL_ADMIN_NAME:admin}
    test-user-password: ${MOPL_TEST_USER_PASSWORD:1234}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${MOPL_S3_REGION:ap-northeast-2}
    bucket: ${MOPL_S3_BUCKET:mopl-bucket}
    profile-image-path: ${AWS_S3_PROFILE_PATH:profiles/}
    content-thumbnail-path: ${AWS_S3_CONTENT_THUMBNAIL_PATH:thumbnails/custom/}
