plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':mopl-core')
    implementation project(':mopl-infrastructure:db')
    implementation project(':mopl-infrastructure:kafka')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    implementation 'software.amazon.awssdk:s3:2.40.17'

    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // Email 전송
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // 재시도 메커니즘
    implementation 'org.springframework.retry:spring-retry:2.0.5'
    implementation 'org.springframework:spring-aspects'
}
